apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/single-repo.git
    targetRevision: HEAD
    path: app1/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true