apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging
  template:
    metadata:
      labels:
        app: staging
    spec:
      containers:
      - name: staging
        image: nginx
        ports:
        - containerPort: 80