apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-example
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            namespace: dev
            url: https://kubernetes.default.svc
          - cluster: staging
            namespace: staging
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Yashsharma1911/argocd-sample.git
        targetRevision: main
        path: applicationSet/environments/{{cluster}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
