apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-example-git
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Yashsharma1911/argocd-sample.git
        revision: main
        directories:
          - path: applicationSet/environments/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Yashsharma1911/argocd-sample.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
