apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: nginx
        ports:
        - containerPort: 80